# Configure main menu and social menu
[[main]]
identifier = "stockgains"
name = "StockGainsCalculator"
url = "https://stockgainscalculator.com"
[main.params]
newtab = true

#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fakturk/StockGainsCalculatorBlog"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/fakturk"

[social.params]
icon = "brand-twitter"
